"""initial schema

Revision ID: 2154987c781c
Revises: 
Create Date: 2026-09-19 08:21:00.690294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '2154987c781c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('incidents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bbox', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_incidents_bbox', 'incidents', ['bbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('vessels',
    sa.Column('mmsi', sa.String(length=16), nullable=False),
    sa.Column('imo', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vessel_type', sa.String(length=64), nullable=True),
    sa.Column('vessel_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('mmsi')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vessel_mmsi', sa.String(length=16), nullable=False),
    sa.Column('spatial_score', sa.Float(), nullable=False),
    sa.Column('temporal_score', sa.Float(), nullable=False),
    sa.Column('trajectory_score', sa.Float(), nullable=False),
    sa.Column('behavioural_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['vessel_mmsi'], ['vessels.mmsi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('drift_forecasts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('forecast_hours', sa.Integer(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('model_run_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_drift_forecasts_geometry', 'drift_forecasts', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('environmental_datasets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=128), nullable=False),
    sa.Column('variable', sa.String(length=64), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bbox', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_environmental_datasets_bbox', 'environmental_datasets', ['bbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('evidence_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leading_candidate_mmsi', sa.String(length=16), nullable=True),
    sa.Column('decision_status', sa.String(length=32), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('origin_analyses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('probable_origin_geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('release_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uncertainty_km', sa.Float(), nullable=False),
    sa.Column('ensemble_size', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('density_field_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_origin_analyses_probable_origin_geometry', 'origin_analyses', ['probable_origin_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('satellite_scenes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('polarization', sa.String(length=16), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('scene_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_geospatial_index('idx_satellite_scenes_geometry', 'satellite_scenes', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('vessel_tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vessel_mmsi', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('speed_knots', sa.Float(), nullable=True),
    sa.Column('course_deg', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['vessel_mmsi'], ['vessels.mmsi'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_mmsi', 'timestamp', 'source')
    )
    op.create_geospatial_index('idx_vessel_tracks_geometry', 'vessel_tracks', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('pasha_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('candidate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('release_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('release_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_configuration', sa.JSON(), nullable=False),
    sa.Column('simulation_status', sa.String(length=32), nullable=False),
    sa.Column('result_geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('spatial_overlap', sa.Float(), nullable=True),
    sa.Column('centroid_distance_km', sa.Float(), nullable=True),
    sa.Column('temporal_error_h', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_pasha_runs_release_location', 'pasha_runs', ['release_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_pasha_runs_result_geometry', 'pasha_runs', ['result_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('spill_detections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scene_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('orientation_deg', sa.Float(), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('width_km', sa.Float(), nullable=True),
    sa.Column('compactness', sa.Float(), nullable=True),
    sa.Column('detection_score', sa.Float(), nullable=False),
    sa.Column('classification_label', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('analyst_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['satellite_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_spill_detections_centroid', 'spill_detections', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_spill_detections_geometry', 'spill_detections', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('falsification_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pasha_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spatial_test', sa.Boolean(), nullable=False),
    sa.Column('temporal_test', sa.Boolean(), nullable=False),
    sa.Column('drift_test', sa.Boolean(), nullable=False),
    sa.Column('physical_test', sa.Boolean(), nullable=False),
    sa.Column('behavioural_signal', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('pass_fail', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pasha_run_id'], ['pasha_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('falsification_results')
    op.drop_geospatial_index('idx_spill_detections_geometry', table_name='spill_detections', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_index('idx_spill_detections_centroid', table_name='spill_detections', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('spill_detections')
    op.drop_geospatial_index('idx_pasha_runs_result_geometry', table_name='pasha_runs', postgresql_using='gist', column_name='result_geometry')
    op.drop_geospatial_index('idx_pasha_runs_release_location', table_name='pasha_runs', postgresql_using='gist', column_name='release_location')
    op.drop_geospatial_table('pasha_runs')
    op.drop_geospatial_index('idx_vessel_tracks_geometry', table_name='vessel_tracks', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('vessel_tracks')
    op.drop_geospatial_index('idx_satellite_scenes_geometry', table_name='satellite_scenes', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('satellite_scenes')
    op.drop_geospatial_index('idx_origin_analyses_probable_origin_geometry', table_name='origin_analyses', postgresql_using='gist', column_name='probable_origin_geometry')
    op.drop_geospatial_table('origin_analyses')
    op.drop_table('evidence_reports')
    op.drop_geospatial_index('idx_environmental_datasets_bbox', table_name='environmental_datasets', postgresql_using='gist', column_name='bbox')
    op.drop_geospatial_table('environmental_datasets')
    op.drop_geospatial_index('idx_drift_forecasts_geometry', table_name='drift_forecasts', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('drift_forecasts')
    op.drop_table('candidates')
    op.drop_table('vessels')
    op.drop_geospatial_index('idx_incidents_bbox', table_name='incidents', postgresql_using='gist', column_name='bbox')
    op.drop_geospatial_table('incidents')
    # ### end Alembic commands ###
